# Generated by Django 3.2 on 2023-10-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='processor',
            field=models.CharField(max_length=512),
        ),
    ]
