# Generated by Django 3.2 on 2023-10-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_challenge_processor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
