# Generated by Django 3.2 on 2023-10-18 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_processor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.processor'),
        ),
    ]
