# Generated by Django 3.2 on 2023-10-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_challenge_processor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='processor',
        ),
        migrations.CreateModel(
            name='ChallengeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.challenge')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.processor')),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.challengevariant'),
        ),
    ]
