# Generated by Django 3.2 on 2024-05-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20231021_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='fileSize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='paramsNb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
