# Generated by Django 3.2 on 2023-08-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='rank',
            field=models.CharField(choices=[('Professor', 'Professor'), ('PhD Student', 'PhD Student'), ('Engineer', 'Engineer'), ('Other', 'Other')], default='PhD Student', max_length=20),
        ),
    ]
