# Generated by Django 3.2 on 2023-08-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='video',
            new_name='youtube_video',
        ),
    ]
