# Generated by Django 3.2 on 2023-08-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_video_application_youtube_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='youtube_video',
        ),
        migrations.AddField(
            model_name='application',
            name='youtube_video_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
