# Generated by Django 3.2 on 2023-08-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230831_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='short_description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
