# Generated by Django 3.2 on 2023-08-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230831_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
