# Generated by Django 3.2 on 2023-10-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_partner_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('header', models.ImageField(upload_to='')),
                ('short_content', models.TextField(max_length=2048)),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
    ]
