version: '3.2'

services:
  web:
    container_name: deepilia-web
    build:
      context: ./deepilia

    # use django dev server
    # command: python manage.py runserver 0.0.0.0:8000

    # use gunicorn
    command: gunicorn deepilia.wsgi:application --bind 0.0.0.0:8000

    restart: always
    volumes:
      - ./deepilia/static:/static
      - ./deepilia/media:/media
      - ./deepilia:/code 
    environment: 
      - DEBUG=False
    # ports:
    #   - 8000:8000
    networks:
      - deepilianet

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: deepilia-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - URL=deepilia.com
      - SUBDOMAINS=www,
      - VALIDATION=http
    volumes:
      - ./deepilia/media:/media
      - ./deepilia/static:/static
      - ./configs/nginx.conf:/config/nginx/nginx.conf
      - ./configs/deepilia.conf:/config/nginx/site-confs/deepilia.conf
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - deepilianet

networks:
  deepilianet: